[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.build]
cacheDirs = ["node_modules"]
cmds = [
  "npm ci --prefer-offline --no-audit --progress=false",
  "npm run build --if-present"
]

[start]
cmd = "npm start"
