[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/"
healthcheckTimeout = 5

[source]
type = "git"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=512"
