[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "bun run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[source]
type = "git"

[variables]
NODE_ENV = "production"
PORT = "3000" 