name: ✨ Feature Request
description: Предложить новую функциональность или улучшение
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        🕉️ **Благодарим за желание улучшить VibeCode Bible!**

        > *"Креативность - это разум, развлекающийся"* - Альберт Эйнштейн

        Ваши идеи помогают проекту развиваться осознанно и гармонично.

  - type: textarea
    id: problem
    attributes:
      label: 🤔 Проблема или потребность
      description: Какую проблему решает эта функция? Как она улучшит опыт пользователей?
      placeholder: Опишите проблему, которую вы хотите решить...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Предлагаемое решение
      description: Четкое описание того, что вы хотите добавить.
      placeholder: Опишите ваше решение...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Альтернативы
      description: Рассматривали ли вы другие решения? Какие есть варианты?
      placeholder: Опишите альтернативные подходы...

  - type: dropdown
    id: category
    attributes:
      label: 📂 Категория
      description: К какой области относится ваше предложение?
      options:
        - Bot Functionality
        - Developer Experience
        - Testing Framework
        - Documentation
        - Performance
        - Security
        - UI/UX
        - Architecture
        - Tooling
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: ⭐ Приоритет
      description: Насколько важна эта функция?
      options:
        - Low - Nice to have
        - Medium - Would be useful
        - High - Important for workflow
        - Critical - Blocking current work
    validations:
      required: true

  - type: checkboxes
    id: complexity
    attributes:
      label: 🧩 Сложность реализации (ваша оценка)
      description: Как вы оцениваете сложность реализации?
      options:
        - label: Simple - можно реализовать за день
        - label: Medium - потребует несколько дней
        - label: Complex - значительные изменения архитектуры
        - label: Epic - требует планирования и нескольких этапов

  - type: textarea
    id: acceptance
    attributes:
      label: ✅ Критерии приемки
      description: Как мы поймем, что функция реализована правильно?
      placeholder: |
        - [ ] Пользователь может...
        - [ ] Система должна...
        - [ ] Документация обновлена...

  - type: textarea
    id: mockups
    attributes:
      label: 🎨 Мокапы или примеры
      description: Есть ли у вас примеры интерфейса, API или поведения?
      placeholder: Приложите скриншоты, схемы или ссылки на примеры...

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Готовность к участию
      description: Готовы ли вы помочь с реализацией?
      options:
        - label: Я готов обсудить детали реализации
        - label: Я могу помочь с написанием кода
        - label: Я могу помочь с тестированием
        - label: Я могу помочь с документацией
        - label: Я готов предоставить обратную связь во время разработки

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Checklist
      description: 'Пожалуйста, подтвердите следующее:'
      options:
        - label: 'Я проверил, что такой функции еще нет'
          required: true
        - label: 'Я искал похожие предложения в issues'
          required: true
        - label: 'Я готов помочь с реализацией или тестированием'
          required: false
